.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "JT" "1" "November 2016" "" "JT MANUAL"
.
.SH "NAME"
\fBjt\fR \- transform JSON data to tabular format
.
.SH "SYNOPSIS"
\fBjt\fR \fB[\-hV]\fR
.
.br
\fBjt\fR [\fB\-j\fR] [\fBCOMMAND\fR \.\.\.]
.
.SH "DESCRIPTION"
\fBJt\fR transforms JSON data structures into tables of columns and rows for processing in the shell\. Extracting information from deeply nested JSON data is difficult and unreliable with tools like \fBsed\fR and \fBawk\fR, and tools that are specially designed for manipulating JSON are cumbersome to use in the shell because they either return their results as JSON or introduce a new turing complete scripting language that needs to be quoted and constructed via string interpolation\.
.
.P
\fBJt\fR provides only what is needed to extract data from nested JSON data structures and organize the data into a table\. Tools like \fBcut\fR, \fBpaste\fR, \fBawk\fR, \fBjoin\fR, \fBsort\fR, \fBuniq\fR, etc\. can be used to efficiently reduce the tabular data to the final result\.
.
.P
\fBJt\fR accepts JSON input (UTF\-8) on \fBstdin\fR and writes output to \fBstdout\fR\. The input stream may contain multiple JSON forms separated by whitespace (i\.e\. \fBSPACE\fR, \fBHT\fR, \fBCR\fR, or \fBLF\fR)\.
.
.SH "OPTIONS"
.
.TP
\fB\-h\fR
Print usage info and exit\.
.
.TP
\fB\-V\fR
Print version and license info and exit\.
.
.TP
\fB\-j\fR
Inner join mode: discard rows with missing columns\.
.
.TP
\fB\-s\fR
Included for compatibility with earlier versions\.
.
.TP
\fB\-u\fR \fIstring\fR
Unescape JSON \fIstring\fR, print it, and exit\.
.
.SH "COMMANDS"
Non\-option arguments are commands in a limited stack\-based programming language\. There are a number of stacks provided by the \fBjt\fR runtime:
.
.IP "\(bu" 4
The \fBdata stack\fR contains JSON objects from the input stream\. Commands operate on the top of this stack to traverse the JSON tree and print values\.
.
.IP "\(bu" 4
The \fBgosub stack\fR contains pointers into the data stack\. Commands push data stack pointers onto this stack to save the state of the data stack and pop them off to restore the data stack to a saved state\.
.
.IP "\(bu" 4
The \fBindex stack\fR contains the indexes of nested arrays as \fBjt\fR iterates over them\. Commands can print the value at the top of this stack\.
.
.IP "" 0
.
.P
\fBJt\fR provides the following commands:
.
.TP
\fB[\fR
Save the state of the data stack: the current data stack pointer is pushed onto the gosub stack\.
.
.TP
\fB]\fR
Restore the data stack to a saved state: pop the gosub stack and restore the data stack pointer to that state\.
.
.TP
\fB%\fR
Print the value at the top of the data stack\. If the item at the top of the data stack is not a string or primitive type its JSON representation is printed\. See the \fBOUTPUT FORMAT\fR section below for details\.
.
.TP
\fB^\fR
Print the array index or object key at the top of the index stack\. Note that the index stack will always have at least one item \(em the index of the current JSON object read from stdin\.
.
.TP
\fB@\fR
Print the keys of the object at the top of the data stack\. If the top of the data stack is not an object then its type is printed in brackets, eg\. \fB[string]\fR, \fB[number]\fR, \fB[boolean]\fR, or \fB[null]\fR\. If there is no value then \fB[none]\fR is printed\.
.
.TP
\fB\.\fR
Iterate over the values of the object at the top of the data stack\. The current value will be pushed onto the data stack and the current key will be pushed onto the index stack\.
.
.TP
\fB[\fR\fIKEY\fR\fB]\fR
Drill down: get the value of the \fIKEY\fR property of the object at the top of the data stack and push that value onto the data stack\.
.
.IP
If the item at the top of the data stack is not an object or if the object has no \fIKEY\fR property a blank field is printed, unless the \fB\-j\fR option was specified in which case the entire row is removed from the output\.
.
.IP
If the \fIKEY\fR property of the object is an array subsequent commands will operate on one of the items in the array, chosen automatically by \fBjt\fR\. The array index will be available to subsequent commands via the index stack\.
.
.TP
\fIKEY\fR
See \fB[\fR\fIKEY\fR\fB]\fR above \(em the \fB[\fR and \fB]\fR may be omitted if the property name \fIKEY\fR does not conflict with any \fBjt\fR command\.
.
.TP
\fB^\fR\fIKEY\fR
See \fIKEY\fR above \(em this variant drills down to the first property of the object whose name starts with \fIKEY\fR\. The match is not case sensitive\.
.
.P
When \fBjt\fR starts, the root JSON object is pushed onto the data stack\. Then commands are evaluated, from left to right\. When a JSON array is pushed onto the data stack a corresponding index (starting at zero) is pushed onto the index stack, and the associated object in the array at that index is automatically pushed onto the data stack\.
.
.P
When all commands have been evaluated, each item in the output stack is printed, separated by tabs, the data stack is restored to its initial state (containing only the root JSON object), and evaluation begins again, evaluating the commands from left to right\.
.
.P
Each iteration will increment indices stored in the index stack such that all iterations follow a different path through the nested JSON tree, each traversing a different permuation of array indices\. You can think of this process as an implicit join, if that helps\.
.
.SH "OUTPUT FORMAT"
The format of printed output from \fBJt\fR (see \fB%\fR in \fBCOMMANDS\fR, above) depends on the type of thing being printed:
.
.SS "Primitives"
JSON primitives (i\.e\. \fBnull\fR, \fBtrue\fR, and \fBfalse\fR) and numbers are printed verbatim\. \fBJt\fR does not process them in any way\. Numbers can be of arbitrary precision, as long as they conform to the JSON parsing grammar\.
.
.P
If special formatting is required the \fBprintf\fR program is your friend:
.
.IP "" 4
.
.nf

$ printf %\.0f 2\.99792458e9
2997924580
.
.fi
.
.IP "" 0
.
.SS "Strings"
Strings are printed verbatim, minus the enclosing double quotes\. No unescaping is performed because tabs or newlines in JSON strings would break the tabular output format\.
.
.P
If unescaped values are desired the \fB\-u\fR option can be used:
.
.IP "" 4
.
.nf

$ jt \-u \'i love music \eu266A\'
i love music ♪
.
.fi
.
.IP "" 0
.
.SS "Collections"
Objects and arrays are printed as JSON, with insignificant whitespace omitted\.
.
.SH "EXAMPLES"
We will use the following JSON input for the examples:
.
.IP "" 4
.
.nf

$ JSON=\'{"foo":"a","bar":{"x":"b"},"baz":[{"y":"c"},{"y":"d","z":"e"}]}\'
.
.fi
.
.IP "" 0
.
.P
We pretty\-print it here for reference:
.
.IP "" 4
.
.nf

{
    "foo": "a",
    "bar": {
        "x": "b"
    },
    "baz": [
        {
            "y": "c"
        },
        {
            "y": "d",
            "z": "e"
        }
    ]
}
.
.fi
.
.IP "" 0
.
.SS "Explore"
Explore JSON data, print an object\'s keys:
.
.IP "" 4
.
.nf

$ echo "$JSON" | jt @
foo
bar
baz
.
.fi
.
.IP "" 0
.
.P
Print a nested object\'s keys:
.
.IP "" 4
.
.nf

$ echo "$JSON" | jt bar @
x
.
.fi
.
.IP "" 0
.
.P
Same as above, with fuzzy property name matching:
.
.IP "" 4
.
.nf

$ echo "$JSON" | jt ^b @
x
.
.fi
.
.IP "" 0
.
.P
Print the keys of the first object in a nested array:
.
.IP "" 4
.
.nf

$ echo "$JSON" | jt baz @
y
.
.fi
.
.IP "" 0
.
.P
Print the indexes in a nested array:
.
.IP "" 4
.
.nf

$ echo "$JSON" | jt baz ^
0
1
.
.fi
.
.IP "" 0
.
.SS "Extract"
Extract values from JSON data:
.
.IP "" 4
.
.nf

$ echo "$JSON" | jt foo %
a
.
.fi
.
.IP "" 0
.
.P
Extract nested JSON data:
.
.IP "" 4
.
.nf

$ echo "$JSON" | jt bar x %
b
.
.fi
.
.IP "" 0
.
.SS "Save / Restore"
Extract multiple values by saving and restoring the data stack:
.
.IP "" 4
.
.nf

$ echo "$JSON" | jt [ foo % ] bar x %
a       b
.
.fi
.
.IP "" 0
.
.SS "Arrays"
Iterate over nested arrays, producing one row per iteration:
.
.IP "" 4
.
.nf

$ echo "$JSON" | jt [ foo % ] [ bar x % ] baz y %
a       b       c
a       b       d
.
.fi
.
.IP "" 0
.
.P
Include the array index as a column in the result:
.
.IP "" 4
.
.nf

$ echo "$JSON" | jt [ foo % ] [ bar x % ] baz y % ^
a       b       c       0
a       b       d       1
.
.fi
.
.IP "" 0
.
.SS "Objects"
Iterate over the values of an object without specifying intermediate keys:
.
.IP "" 4
.
.nf

$ echo $JSON | jt baz \. %
c
d
e
.
.fi
.
.IP "" 0
.
.P
Iterate over the keys and values of an object without specifying intermediate keys:
.
.IP "" 4
.
.nf

$ echo $JSON | jt baz \. ^ %
y       c
y       d
z       e
.
.fi
.
.IP "" 0
.
.SS "Joins"
Notice the empty column \(em some objects don\'t have the \fIz\fR key:
.
.IP "" 4
.
.nf

$ echo "$JSON" | jt [ foo % ] baz [ y % ] z %
a       c
a       d       e
.
.fi
.
.IP "" 0
.
.P
Inner join mode will remove rows from the output when any key in the traversal path doesn\'t exist:
.
.IP "" 4
.
.nf

$ echo "$JSON" | jt \-j [ foo % ] baz [ y % ] z %
a       d       e
.
.fi
.
.IP "" 0
.
.SH "COPYRIGHT"
Copyright © 2016 Micha Niskin \fB<micha\.niskin@gmail\.com>\fR\. Distributed under the Eclipse Public License, version 1\.0\.
.
.SH "SEE ALSO"
jshon(1), jq(1), comm(1), diff(1), sort(1), join(1), uniq(1), bash(1)
